@startuml
'https://plantuml.com/class-diagram

Rover }-- Plateau
Rover -- Direction


class Plateau {
- X_MIN: int = 0
- Y_MIN: int = 0
- xmax: int
- ymax: int

+ move(x: int, y: int, d: Direction): String
- collisionCheck(): String
- edgeCheck(): boolean
}

class Rover {
  - posX: int
    - posY: int
    - d: Direction

    + goLeft()
    + goRight()
    + move(): String
    + processMovement(movement: String) : String
    - checkInputString(movement: String) : String
}


enum Direction {
NORTH,
EAST,
SOUTH,
WEST
}

@enduml